# Test container

# FROM alpine:latest

# RUN apk add --no-cache bash

FROM ubuntu:latest
# RUN	useradd -r -u 999 -g mysql mysql
# USER mysql
# Create container
# docker build -t <container-name> .

# Run container
# docker run --rm -it -v $PWD:/tmp <container-name>
