version: "3"

services:
  # MySQL Configuration -----------------
  mysql:
    image: mariadb
    # build: ./requirements/mariadb/
    # container_name: mariadb

    # ports:
    #   - "3306:3306"
    
    # networks:
    #   - inception

    # mount host machine path `data/mysql` in the container path `/var/lib/mysql
    # allows DB files to be stored in the host machine
    # Directory preparation at appA
    volumes:
      - $PWD/data/mysql:/var/lib/mysql
      # - /c/users/isaac/Documents/Programming/42cursus_06_Inception/testfile/data/mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass

    restart: always

  # WordPress Configuration -----------------
  wordpress:
    image: wordpress:php7.3-fpm-alpine

    # mounts the host machine path `data/html` in the container path `/var/www/html`
    # allows WordPress application files to be stored in the host machine instead of the container
    # Directory preparation at AppB
    volumes:
      - $PWD/data/html:/var/www/html
      # - /c/users/isaac/Documents/Programming/42cursus_06_Inception/testfile/data/html:/var/www/html

    # states that WordPress service is dependent on the mysql service
    # implies that the services are started and stopped in the dependency order
    depends_on:
      - mysql

    # networks:
    #   - inception

    # match it with MariaDB's envirnmental variables
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_

    # enables the WordPress service to communicate with the mysql service
    links:
      - mysql

    restart: always

  # NGINX Configuration -----------------
  nginx:
    image: nginx:alpine

    # host path `data/html` has to match the host path mentioned in the WordPress configuration
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - $PWD/nginx:/etc/nginx/conf.d
      - $PWD/data/html:/var/www/html
      # - /c/users/isaac/Documents/Programming/42cursus_06_Inception/testfile/nginx:/etc/nginx/conf.d
      # - /c/users/isaac/Documents/Programming/42cursus_06_Inception/testfile/data/html:/var/www/html

    # networks:
    #   - inception

    # maps the host machine port 8080 to the container port 80
    ports:
      - 8080:80

    # enables the NGINX service to communicate with the WordPress service
    links:
      - wordpress

    # provide a nginx.config in AppC


# networks:
#   inception:
#     driver: bridge
